name: dryrun

on: 
  push:
  pull_request:
    branches: [ "master" ]
      
# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:service::role
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.3

    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: true

    - name: Terraform List
      id: list
      run: terraform state list
  
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
   
    - name: Terraform Validate
      id: validation
      run: terraform validate
      continue-on-error: false

      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: true
   
